name: CordsBook
main: com.mixed.plugin.Main
version: 1.1
author: Mixed
description: CordsBook
commands:
  sc:
    description: <name> Save current cords of your location
  lic:
    description: lists all your saved cords
  remove:
    description: <name> removes a loction from your list